### ISSUE TITLE
Visual/UX review

### ISSUE THREAD

**Issue by bdrtsky** [nuxt/nuxt.com#272]
- [ ] Roobert font looses it's "modern" look on bold weights, I'd use max Semi Bold weight for it in every heading (add more font size instead)
- [ ] Roobert font has lot's of stylistic set options, like this, compare "y" (font-feature-settings: "ss03")

<img width="641" alt="Screenshot 2022-04-05 at 18 07 38" src="https://user-images.githubusercontent.com/45076741/161789876-797bcaa2-a13d-464c-915f-78ecc265f282.png">

<img width="641" alt="Screenshot 2022-04-05 at 18 07 24" src="https://user-images.githubusercontent.com/45076741/161789900-aee7f3d2-bc4c-44de-a229-cb6d024ad237.png">

- [ ] show dropdown on header navigation links on hover, instead of click (#285)
- [x] dropdown surface looks blurred with background and header, especially on small screens (border/shadow/background/positioning to show it's floating surface could fix this)

<img width="1019" alt="Screenshot 2022-04-05 at 18 29 57" src="https://user-images.githubusercontent.com/45076741/161790191-27f36aaf-9b76-438a-a981-7d8fb75450d5.png">

- [ ] white/black contrast button in header looks like it has broken color mode styling (I think primary color is better for CTA)
- [x] hamburger menu icon is boring and too small
- [x] different container padding for header and overlaying mobile menu (open/close hamburger button sitting in different places)

https://user-images.githubusercontent.com/45076741/161790407-db405256-5b76-4897-b582-aa4c83f8023d.mp4

- [x] text size is too small in lot's of places (overlay navigation menu, ...). can hardly read it, also small tap area for touch screens

<img width="432" alt="Screenshot 2022-04-05 at 18 33 03" src="https://user-images.githubusercontent.com/45076741/161790852-2b8a4087-828e-40b3-b0b1-aaa8372d2d85.png">

- [x] overlay scrim background is too light in dark mode

<img width="718" alt="Screenshot 2022-04-05 at 18 34 21" src="https://user-images.githubusercontent.com/45076741/161791059-dfd5a3c8-8054-4ad7-be65-267efe6b206a.png">

- [ ] native scrollbars looks bad in dark mode (nuxtlabs/nuxt.com#287)
- [ ] nested navigation in mobile overlay menu looks crowded because of vertical line effect (nuxtlabs/nuxt.com#297)

<img width="718" alt="Screenshot 2022-04-05 at 18 35 04" src="https://user-images.githubusercontent.com/45076741/161791303-b529765d-8eaf-476e-ac25-3149779166b3.png">

- [x] ToC is missing on mobile view
- [x] ToC scrollspy doesn't work
- [x] not sure about putting Prev/Next in ToC
- [x] what Play button in ToC means?

<img width="267" alt="Screenshot 2022-04-05 at 18 36 22" src="https://user-images.githubusercontent.com/45076741/161791589-031ea821-a949-4155-9a72-3c7bcfb0c8a5.png">

- [ ] nested ToC items has unreadable text size
- [x] scroll to top on click on ToC items (and text headings) is broken
- [x] right aligning and truncating of ToC items looks weird

<img width="214" alt="Screenshot 2022-04-05 at 18 23 22" src="https://user-images.githubusercontent.com/45076741/161791724-2bd0e03e-8d17-4c11-a3c0-a85419b6f3fd.png">

- [ ] prose text font size is too small
- [ ] prose underlines in headings interfere reading (maybe adding some space will fix, but I'd remove it completely)
- [ ] prose no hover effect on clickable headings
- [ ] prose code snippets highlightning doesn't feel like a part of whole design

More general suggestions:
- [ ] full screen container, without max-width
- [ ] much bigger font sizes almost everywhere, including buttons
- [ ] do not use very bold Roobert
