### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by benjamincanac** [nuxt/nuxt.com#533]
The goal here is to migrate all of our websites around `nuxt.com` without the multi-source. All the documentations stays on `*.nuxt.com` subdomains.

## Nuxt.com

- [x] Landing page nuxtlabs/nuxt.com#405
- [x] Framework v3
  - [x] Landing page nuxtlabs/nuxt.com#406
  - [x] Links to `v3.nuxtjs.org` (`v3.nuxt.com`) nuxtlabs/nuxt.com#539
- [x] Framework v2
  - [x] Landing page
  - [x] Links to `nuxtjs.org` (`v2.nuxt.com`) nuxtlabs/nuxt.com#539
- [x] Integrations
  - [x] Landing page (list of modules)
  - [x] Links as filters (`officials`/`community`/`3rd party`) nuxtlabs/nuxt.com#538
- [x] Projects page nuxtlabs/nuxt.com#403
- [x] Resources
  - [x] Blog
  - [x] Case Studies
  - [x] Design Kit
  - [x] Live Events
  - [x] Showcases
- [x] Community
  - [x] About nuxtlabs/nuxt.com#541
  - [x] Guide nuxtlabs/nuxt.com#542
  - [x] Repositories nuxtlabs/nuxt.com#525
  - [x] Nuxters nuxtlabs/nuxt.com#543
  - [x] Partners nuxtlabs/nuxt.com#526
- [x] Company
  - [x] About
  - [x] Careers
  - [x] Partners nuxtlabs/nuxt.com#540
  - [x] Support
  - [x] Contact
