### ISSUE TITLE
`v2.nuxt.com`

### ISSUE THREAD

**Issue by benjamincanac** [nuxt/nuxt.com#534]
- [ ] Move to `nuxt/nuxt.js` repository in `docs/`
- [ ] Branch + deployment on domain
- [ ] Upgrade to new docus (`nuxt3-docs` theme https://github.com/nuxt/nuxt3-docs)
- [ ] Remove landing page
- [ ] Update logo
- [ ] Link to go back to `nuxt.com`

### Navbar

1. Learn
  - ...docs
  - Master courses to `https://masteringnuxt.com/?utm_source=nuxt&utm_medium=link&utm_campaign=nsite`
2. Examples
3. Explore
  - Deployments
  - Themes
  - Video courses
  - Modules to `nuxt.com/integrations`
4. Releases

#### Discover

- [ ] Redirect `/showcases` to `nuxt.com/resources/showcases`
- [ ] Redirect `/case-studies` to `nuxt.com/resources/case-studies`
- [ ] Redirect `/testimonials` to `nuxt.com/docs/framework/v2`

#### Learn

- [ ] Redirect `/tutorials` to `nuxt.com/resources/blog`

#### Community

- [ ] Redirect `/announcements` to `nuxt.com/resources/blog`
- [ ] Redirect `/teams` to `nuxt.com/community/nuxters`
- [ ] Redirect `/sponsors` to `nuxt.com/community/partners`

#### Partners

- [ ] Redirect `/partners` to `nuxt.com/community/partners`

### Footer

- [ ] Default docus footer
- [ ] `/support` -> `nuxt.com/company/support`
- [ ] `/contribution-guide` (to keep)
- [ ] `/events` -> `nuxt.com/resources/live-events` + update on `nuxt.com`
- [ ] `/design` -> `nuxt.com/resources/design-kit`
