### ISSUE TITLE
`image.nuxt.com`

### ISSUE THREAD

**Issue by benjamincanac** [nuxt/nuxt.com#537]
- [ ] Branch deployment on domain
- [ ] Upgrade to `nuxt3`
- [ ] Documentation with latest docus
- [ ] Link to go back to nuxt.com
